### PR TITLE
Added more optional arguments to CreateTempAccount

### PR DESCRIPTION
**Pull request by Dantemss**
To set fields in the created account (locally only)

### CODE REVIEW

**Comment by karenc** [comment]
:+1:

**Comment by jpslav** [comment]
Um  I already merged this, but does this need infrastructure to get the names over to OX Accounts?  (or is that done via the existing sync mechanism?)

**Comment by karenc** [comment]
No @Dantemss said it only saves the names locally.  There's currently no way of updating the names in OX Accounts yet.

**Comment by Dantemss** [comment]
Released v 5.2.0

**Pull request merged**
